name: Bug report
description: Report a bug or vulnerability in this application

body:
  - type: dropdown
    id: bug-regression
    attributes:
      label: Is this bug a regression?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Brief description of the bug
    validations:
      required: true

  - type: textarea
    id: how-was-happened
    attributes:
      label: How did you see the bug? (Context)
    validations:
      required: true